routes/authenticate.py
"""This file handles authentication tokens if a user wants to login inorder to change something"""

from flask import Blueprint, flash
from flask import render_template, request, redirect, url_for, session
import json
from functools import wraps
import requests
from mycarapp import API_BASE_URL


auth_bp = Blueprint('login', __name__)

header = {'token': None}

LOGIN_STATUS = False

page_data = {'login_status': None}


@auth_bp.route('/login/', methods=['GET', 'POST'])
def home():
    global LOGIN_STATUS
    if LOGIN_STATUS is True:
        print("You are already logged in ")
        return redirect(url_for('car.home'))
    elif request.method == 'GET':
        session['original_url'] = request.referrer
        return render_template('login.html', page_data=page_data)
    elif request.method == 'POST':
        try:
            print("Getting token for the user")
            # Code to execute when the method is POST
            username = request.form['username']
            password = request.form['password']
            payload = {'password': password, 'username': username}
            # Generate JWT token
            response = requests.post(f'{API_BASE_URL}/login', data=payload)
            token = json.loads(response.text)['token']
            session['token'] = token  # Store the token in the session object
            LOGIN_STATUS = True
            print(header)
            print(f"Your Login Status is now {LOGIN_STATUS}")
            original_url = session.pop('original_url', None)  # Get the original request URL from the session
            if original_url:
                return redirect(original_url)
            else:
                return redirect(url_for('car.home'))
        except Exception as e:
            print(e)
            flash('Error! Invalid User Name or Password', 'danger')
            return redirect(url_for('login.home'))


def get_login_status():
    print(f"Giving latest login status that is {LOGIN_STATUS}")
    return LOGIN_STATUS


def login_required(route_function):
    @wraps(route_function)
    def wrapper(*args, **kwargs):
        login_status = get_login_status()
        if login_status is not True:
            print("You are need to logged in")
            return redirect(url_for('login.home'))
        else:
            header['token'] = session.get('token')  # Use the token from the session object
            return route_function(*args, **kwargs)

    return wrapper


@auth_bp.route('/logout/', methods=['GET', 'POST'])
def logout():
    global LOGIN_STATUS
    LOGIN_STATUS = False
    return redirect(url_for('car.home'))

routes/cars_routes.py
"""
This file handles all REST API calling and receiving of cars
"""
from flask import Blueprint

from flask import flash, render_template, request, redirect, url_for
import requests
from auxilaryapi import get_image_link
from routes.authenticate import header, get_login_status, login_required
from mycarapp import API_BASE_URL



car_bp = Blueprint('car', __name__)

page_data = {'login_status': None}


@car_bp.route('/')
def home():
    """
    Gets cars information from API endpoint and renders it on home.html

    Returns:
        Rendered HTML page for cars information
    Raises:
        ConnectionError: If connection fails with endpoint API
        TimeOutError : If request takes longer then 20 seconds
    Usages:
        call this function from route in Flask web application to display cars information
    """
    page_data['login_status'] = get_login_status()
    response = requests.get(f'{API_BASE_URL}cars/')
    cars = response.json()
    # don't show cars that are returned
    cars = [car for car in cars if car['status'] != 'returned']
    status = request.args.get('status', 'all')
    if status == 'rented':
        print("Getting Rented Cars")
        cars = [car for car in cars if car['status'] == 'rented']
    elif status == 'available':
        print("Getting Available Cars")
        cars = [car for car in cars if car['status'] == 'available']
    else:
        print("Showing all cars")

    return render_template('home.html', cars=cars, login_status=get_login_status, page_data=page_data)


@car_bp.route('/car/<int:car_id>')
def car_details(car_id):
    """
    Gets car detail information from API endpoint and renders it on car_details.html

    Args:
        car_id: id of car record which needs to be displayed
    Returns:
        Rendered HTML page for car detail information
    Raises:
        ConnectionError: If connection fails with endpoint API
        TimeOutError : If request takes longer then 20 seconds
    Usages:
        call this function from route in Flask web application to display car details of one record
    """
    page_data['login_status'] = get_login_status()
    response = requests.get(f'{API_BASE_URL}car/{car_id}', timeout=20)
    car_data = response.json()
    car = car_data[0] if car_data else {}

    keys = list(car.keys())
    keys.remove('id')
    keys.remove('links')
    print(f"Car name is {car['name']}")
    image_link = get_image_link(car)
    # image_link = "https://i.ytimg.com/vi/cDGM76Ig9zM/maxresdefault.jpg"
    return render_template('car_details.html', car=car, keys=keys, image_link=image_link, page_data=page_data)


@car_bp.route('/car/<int:car_id>/delete', methods=['POST'])
@login_required
def delete_car(car_id):
    """
     Deletes car record from API endpoint and navigates to home.html to render cars records on home.html

     Args:
         car_id: id of car record which needs to be deleted
     Returns:
         Rendered HTML page for car detail information
         Error : if the deletes operation not performed
     Raises:
         ConnectionError: If connection fails with endpoint API
         TimeOutError : If request takes longer then 20 seconds
     Usages:
         call this function from route in Flask web application to delete car information
     """
    response = requests.delete(f'{API_BASE_URL}car/{car_id}', headers=header)
    if response.status_code == 204:
        return redirect(url_for('car.home'))
    return f'Error: {response.status_code}', response.status_code


@car_bp.route('/car/<int:car_id>/edit', methods=['GET', 'POST', 'PUT'])
@login_required
def edit_car(car_id):
    """
     Edits car  information from API endpoint and renders it on edit_car.html

     Args:
         car_id: id of car record which needs to be updated
     Returns:
         Rendered HTML page for car detail information if  error occurs
         Rendered HTML page of car information if successfull
     Raises:
         ConnectionError: If connection fails with endpoint API
         TimeOutError : If request takes longer then 20 seconds
     Usages:
         call this function from route in Flask web application to display and edit car information
     """
    page_data['login_status'] = get_login_status()
    # Get the existing car from the API
    car = requests.get(f'{API_BASE_URL}car/{car_id}/').json()[0]

    if request.method == 'POST':

        car = {}
        user_inputs = ''
        # looping through form to make it dynamic
        try:
            for key, user_inputs in request.form.items():
                if key == 'rent_price':
                    car[key] = float(user_inputs)
                if key == 'year':
                    car[key] = int(user_inputs)
                else:
                    car[key] = user_inputs
        except ValueError:
            flash(f'Enter Valid Numbers `{user_inputs}`', 'danger')
            return redirect(url_for('car.edit_car', car_id=car_id))
        # Send a PUT request to update the car in the API
        response = requests.put(f'{API_BASE_URL}car/{car_id}/', json=car, timeout=20, headers=header)
        if response.status_code == 204:
            print("Car updated successfully")
            # if the edit is successful go to the car details page
            return redirect(url_for('car.car_details', car_id=car_id))
        # Error updating car
        flash(f'Error updating car. {response.status_code}', 'danger')
        return redirect(url_for('car.edit_car', car_id=car_id, page_data=page_data))

    else:
        print("Rendering Edit form for cars")
        return render_template('edit_car.html', car=car, page_data=page_data)


@car_bp.route('/car/add', methods=['POST', 'GET'])
@login_required
def add_car():
    """
     Adds car  information from API endpoint and renders it on add_car.html

     Returns:
         Rendered HTML page for car detail information if  error occurs
         Rendered HTML page of cars information if successfull
     Raises:
         ConnectionError: If connection fails with endpoint API
         TimeOutError : If request takes longer then 20 seconds
     Usages:
         call this function from route in Flask web application to add car information
     """
    page_data['login_status'] = get_login_status()
    if request.method == 'POST':

        car = {}
        user_inputs = ''
        # looping through form to make it dynamic
        try:
            for key, user_inputs in request.form.items():
                if key == 'rent_price':
                    car[key] = float(user_inputs)
                if key == 'year':
                    car[key] = int(user_inputs)
                else:
                    car[key] = user_inputs
        except ValueError:
            flash(f'Enter Valid Numbers `{user_inputs}`', 'danger')
            return redirect(url_for('car.add_car'))
        # Send a PUT request to update the car in the API
        response = requests.post(f'{API_BASE_URL}cars/', json=car, timeout=20, headers=header)
        if response.status_code == 201:
            print("Car added successfully")
            # if the edit is successful go to the car details page
            flash('Car added successfully', 'success')
            return redirect(url_for('car.home'))
        # Error updating car
        flash(f'Error adding car. {response.status_code}', 'danger')
        return redirect(url_for('car.add_car'))

    else:
        # Get the existing car from the API for keys to make form dynamic
        car = requests.get(f'{API_BASE_URL}car/{2}/', timeout=20).json()[0]
        print("Rendering Add form for cars")
        return render_template('add_car.html', car=car, page_data=page_data)

routes/customers_routes.py
"""
This file handles all REST API calling and receiving of Customers
"""
from flask import Blueprint

from flask import  flash, render_template, request, redirect, url_for
import requests
from routes.authenticate import header, get_login_status, login_required
from mycarapp import API_BASE_URL


customer_bp = Blueprint('customer', __name__)

page_data = {'login_status': None}

@customer_bp.route('/customers/')
def customer_home():
    """
       Gets customers information for API endpoint and renders it on customers.html

       Returns:
           Rendered HTML page for customers information
       Raises:
           ConnectionError: If connection fails with endpoint API
           TimeOutError : If request takes longer then 20 seconds
       Usages:
           call this function from route in Flask web application to display Customers information
       """
    print("Getting customers page")
    page_data['login_status'] = get_login_status()
    response = requests.get(f'{API_BASE_URL}customers/', timeout=20)
    customers = response.json()
    return render_template('customers.html', customers=customers, page_data=page_data)


@customer_bp.route('/customer/<int:customer_id>')
def customer_details(customer_id):
    """
     Gets customer detail information from API endpoint and renders it on customer_details.html

     Args:
         customer_id: id of customer record which needs to be displayed
     Returns:
         Rendered HTML page for customer detail information
     Raises:
         ConnectionError: If connection fails with endpoint API
         TimeOutError : If request takes longer then 20 seconds
     Usages:
         call this function from route in Flask web application to display customer details of one record
     """
    page_data['login_status'] = get_login_status()
    response = requests.get(f'{API_BASE_URL}customer/{customer_id}', timeout=20)
    cust_data = response.json()
    customer = cust_data[0] if cust_data else {}

    keys = list(customer.keys())
    keys.remove('id')
    keys.remove('links')

    return render_template('customer_details.html', cus=customer, keys=keys, page_data=page_data)


@customer_bp.route('/customer/<int:customer_id>/delete', methods=['POST'])
@login_required
def delete_customer(customer_id):
    """
      Deletes customer record from API endpoint and navigates to customer.html to render customers records

      Args:
          customer_id: id of customer record which needs to be deleted
      Returns:
          Rendered HTML page for customer detail information
          Error : if the deletes operation not performed
      Raises:
          ConnectionError: If connection fails with endpoint API
          TimeOutError : If request takes longer then 20 seconds
      Usages:
          call this function from route in Flask web application to delete customer information
      """
    response = requests.delete(f'{API_BASE_URL}customer/{customer_id}', headers=header)
    if response.status_code == 204:
        return redirect(url_for('customer.customer_home'))
    else:
        return f'Error: {response.status_code}', response.status_code


@customer_bp.route('/customer/<int:customer_id>/edit', methods=['GET', 'POST', 'PUT'])
@login_required
def edit_customer(customer_id):
    """
     Edits customer  information from API endpoint and renders it on edit_customer.html

     Args:
         customer_id: id of customer record which needs to be updated
     Returns:
         Rendered HTML page for customer detail information if  error occurs
         Rendered HTML page of customers information if successfull
     Raises:
         ConnectionError: If connection fails with endpoint API
         TimeOutError : If request takes longer then 20 seconds
     Usages:
         call this function from route in Flask web application to display and edit customer information
     """
    # Get the existing customer from the API
    page_data['login_status'] = get_login_status()
    customer = requests.get(f'{API_BASE_URL}customer/{customer_id}/', timeout=20).json()[0]

    if request.method == 'POST':

        customer = {}
        # looping through form to make it dynamic
        for key, value in request.form.items():
            customer[key] = value

        # Send a PUT request to update the customer in the API
        response = requests.put(f'{API_BASE_URL}customer/{customer_id}/', json=customer, timeout=20, headers=header)
        print("after edited", customer)
        if response.status_code == 204:
            # Customer updated successfully
            flash('Customer updated successfully!', 'success')
            return redirect(url_for('customer.customer_details', customer_id=customer_id))
        else:
            # Error updating customer
            flash('Error updating customer. Please try again.', 'danger')
            return redirect(url_for('customer.edit_customer', customer_id=customer_id))

    else:
        # Render the edit customer form
        return render_template('edit_customer.html', customer=customer, page_data=page_data)


@customer_bp.route('/customer/add', methods=['GET', 'POST'])
@login_required
def add_customer():
    """
     Adds customer information to API endpoint and renders it on add_customer.html

     Returns:
         Rendered HTML page for customer detail information if  error occurs
         Rendered HTML page of customer information if successfull
     Raises:
         ConnectionError: If connection fails with endpoint API
         TimeOutError : If request takes longer then 20 seconds
     Usages:
         call this function from route in Flask web application to add customer information
     """
    if request.method == 'POST':

        customer = {}
        # looping through form to make it dynamic
        for key, value in request.form.items():
            if key == 'car_id':
                customer[key] = int(value)
            else:
                customer[key] = value
        # Send a POST request to insert the customer in the API
        response = requests.post(f'{API_BASE_URL}customers/', json=customer, timeout=20, headers=header)
        if response.status_code == 201:
            flash('Customer Inserted successfully!', 'success')
            return redirect(url_for('customer.customer_home'))
        else:
            # Error inserting customer
            flash('Error Inserting customer. Please try again.', 'danger')
            return redirect(url_for('customer.add_customer'))

    else:
        # Get the existing customer from the API to dynamically render form
        customer = requests.get(f'{API_BASE_URL}customer/{3}/', timeout=20).json()[0]
        return render_template('add_customer.html', customer=customer, page_data=page_data)

templates/add_car.html
{% extends 'base.html' %}

{% block content %}
    <h1>Add Car</h1>
<form method="POST" action="{{ url_for('car.add_car') }}">
    {% for key, value in car.items() %}
        {% if key != 'id' and key != 'links' and key != 'status' %}
            <div class="form-group">
                <label for="{{ key }}">{{ key|title }}</label>
                <input type="text" class="form-control" id="{{ key }}" name="{{ key }}" value="{{Nothing}}">
            </div>
        {% endif %}
    {% endfor %}
    <button type="submit" class="btn btn-primary">Add</button>
</form>

    <a href="{{ url_for('car.add_car') }}" onclick="return confirm('Are you sure you want to cancel this car?')">Cancel</a>
{% endblock %}

templates/add_customer.html
{% extends 'base.html' %}

{% block content %}
    <h1>Add Customer</h1>
<form method="POST" action="{{ url_for('customer.add_customer') }}">
    {% for key, value in customer.items() %}
        {% if key != 'id' and key != 'links' and key != 'car_id' %}
            <div class="form-group">
                <label for="{{ key }}">{{ key|title }}</label>
                {% if key == 'registration_date' %}
                    <input type="text" class="form-control" id="{{ key }}" name="{{ key }}" value="{{Nothing}}" autocomplete="off">
                    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
                    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.min.js"></script>
                    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.0/themes/smoothness/jquery-ui.css">
                    <script>
                        var jq = $.noConflict();
                        jq(function() {
                            jq("#{{ key }}").datepicker({
                                dateFormat: "yy-mm-dd",
                                changeMonth: true,
                                changeYear: true,
                                yearRange: "-100:+0"
                            });
                        });
                    </script>
                {% else %}
                    <input type="text" class="form-control" id="{{ key }}" name="{{ key }}" value="">
                {% endif %}
            </div>
        {% endif %}
    {% endfor %}
    <button type="submit" class="btn btn-primary">Add</button>
</form>

    <a href="{{ url_for('customer.add_customer') }}" onclick="return confirm('Are you sure you want to cancel this Customer?')">Cancel Customer</a>
{% endblock %}

templates/add_rental.html
{% extends 'base.html' %}

{% block content %}

<head>

</head>
    <h1>Rent {{car.name}} for {{car.rent_price}} Euro/Day</h1>

<form method="POST" action="{{ url_for('rental.add_rental', car_id=car.id) }}">
  <div class="form-group">
    <label for="customer_id">Select a customer:</label>
    <select name="customer_id" id="customer_id" class="form-control">
      {% for customer in customers %}
        <option value="{{ customer.id }}">{{ customer.name }}</option>
      {% endfor %}
    </select>
  </div>
  <div class="form-group">
    <label for="from_date">From Date:</label>
    <input type="text" name="from_date" id="from_date" class="form-control" autocomplete="off">
  </div>
  <div class="form-group">
    <label for="to_date">To Date:</label>
    <input type="text" name="to_date" id="to_date" class="form-control" autocomplete="off">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.13.0/jquery-ui.min.js"></script>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.13.0/themes/smoothness/jquery-ui.css">

<script>
  var jq = $.noConflict();
  jq(function() {
    jq("#from_date").datepicker({
      dateFormat: "yy-mm-dd",
      changeMonth: true,
      changeYear: true,
      yearRange: "-100:+0"
    });
    jq("#to_date").datepicker({
      dateFormat: "yy-mm-dd",
      changeMonth: true,
      changeYear: true,
      yearRange: "-100:+0"
    });
  });
</script>



{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{{pdata.title}}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <style>
        body {
            padding-top: 5rem;
            margin-bottom: 60px; /* This pushes the content up to make room for the footer */
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="/">Car Rental</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mx-auto justify-content-center">

                <li class="nav-item">
                    <a class="nav-link text-white px-3" href="/customers">Customers</a>
                </li>
                <li class="nav-item">
                   <a class="nav-link text-white px-3" href="/rentals">Rentals</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link  text-white px-3 " href="/car/add"> Add Car</a>
                </li>
                 <li class="nav-item">
                    <a class="nav-link  text-white px-3 " href="/customer/add"> Add Customer</a>
                </li>
            </ul>

        </div>
<ul class="navbar-nav ml-auto">
    {% if page_data.login_status %}
  <li class="nav-item" style="display: flex; align-items: center;">
    <span class="nav-link" style="margin-right: 10px;">WebWolf</span>
    <a class="nav-link" href="{{ url_for('login.logout') }}">Logout</a>
  </li>
    {% else %}
        <li class="nav-item">
            <a class="nav-link" href="/login">Login</a>
        </li>
    {% endif %}
</ul>
    </nav>

   <div class="container">
  {% with messages = get_flashed_messages() %}
    {% if messages %}
      {% for message in messages %}
      <div class="alert{% if 'success' in message %} alert-success{% elif 'Error' in message %} alert-danger{% elif 'Note' in message %} alert-info{% endif %}">
  {{ message }}
        </div>
      {% endfor %}
    {% endif %}
  {% endwith %}
  {% block content %}{% endblock %}
</div>


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

templates/car_details.html
{% extends 'base.html' %}
{% block content %}
<div class="container" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
        <div class="row">
            <div class="col-md-6">
                <table class="table table-bordered table-hover">
                    <tbody>
                    {% for item in keys %}
                        <tr>
                            <td><strong>{{item}}</strong></td>
                            <td>{{ car[item] }}</td>
                        </tr>
                        {% endfor %}

                    </tbody>
                </table>
                <div class="button-row" style="display: flex; justify-content: space-between;">
                    <a href="{{ url_for('car.edit_car', car_id=car.id) }}" class="btn btn-primary">Edit Car</a>
                   <form action="{{ url_for('car.delete_car', car_id=car.id) }}" method="post">
                    <button type="submit" class="btn btn-danger">Delete Car</button>
                </form>
                </div>


            </div>
            <div class="col-md-6">
                <img src="{{ image_link}}"  width="450" height="350" class="img-fluid rounded">
                <div class="mt-3">
                {% if car.status.lower() == 'available' or car.status.lower() == 'returned' %}
                    <h3>Car Is Available For <span class="text-success">{{car.rent_price}}€/Day</span></h3>
                    <a href="{{ url_for('rental.add_rental', car_id=car.id) }}" class="btn btn-lg btn-success">Rent Now</a>
                {% else %}
                    <button class="btn btn-lg btn-danger" disabled>Car Rented</button>
                {% endif %}
            </div>
            </div>


        </div>

    </div>



{% endblock %}

{% block custom_styles %}
  <style>
    .card-title {
      font-size: 1.25rem;
      margin-bottom: 0.5rem;
    }

    .card-text {
      margin-bottom: 0.25rem;
    }

    .card-text:last-child {
      margin-bottom: 0;
    }
  </style>
{% endblock %}

templates/customer_details.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1>Customer Details</h1>
        <hr>
        <div class="row">

            <div class="col-md-6">
                <table class="table table-bordered table-hover">
                    <tbody>
                      {% for item in keys %}
                        <tr>
                            <td><strong>{{item}}</strong></td>
                            <td>{{ cus[item] }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

               <div class="button-row" style="display: flex; justify-content: space-between;">
                     <a href="{{ url_for('customer.edit_customer', customer_id=cus.id) }}" class="btn btn-primary">Edit Customer</a>
                <form action="{{ url_for('customer.delete_customer', customer_id=cus.id) }}" method="post">
                    <button type="submit" class="btn btn-danger">Delete Customer</button>
                </form>

               </div>


            </div>

        </div>
    </div>

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Bootstrap JS -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endblock %}

templates/customers.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="mb-4">Customers ({{ customers|length }})</h1>

  <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for cus in customers %}
      <div class="col">
        <div class="card h-100">
          <div class="card-body">
            <h5 class="card-title">{{ cus.name }} {{ cus.surname }}</h5>
            <p class="card-text">Address: {{ cus.address }}</p>
            <p class="card-text">Phone: {{ cus.phone}}</p>
            <p class="card-text">Registration_date: {{ cus.registration_date }}</p>
            <a href="{{ url_for('customer.customer_details', customer_id=cus.id) }}" class="btn btn-primary">Details</a>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>

{% endblock %}

{% block custom_styles %}
  <style>
    .card-title {
      font-size: 1.25rem;
      margin-bottom: 0.5rem;
    }

    .card-text {
      margin-bottom: 0.25rem;
    }

    .card-text:last-child {
      margin-bottom: 0;
    }
  </style>
{% endblock %}

templates/edit_car.html
{% extends 'base.html' %}

{% block content %}
    <h1>Edit Car: {{ car.maker_name }} {{ car.model }}</h1>
<form method="POST" action="{{ url_for('car.edit_car', car_id=car.id) }}">
    {% for key, value in car.items() %}
        {% if key != 'id' and key != 'links' %}
            <div class="form-group">
                <label for="{{ key }}">{{ key|title }}</label>
                <input type="text" class="form-control" id="{{ key }}" name="{{ key }}" value="{{ value }}">
            </div>
        {% endif %}
    {% endfor %}
    <button type="submit" class="btn btn-primary">Update</button>
</form>

    <a href="{{ url_for('car.delete_car', car_id=car.id) }}" onclick="return confirm('Are you sure you want to delete this car?')">Delete Car</a>
{% endblock %}

templates/edit_customer.html
{% extends 'base.html' %}

{% block content %}
    <h1>Edit Customer: {{ customer.name }} {{ customer.surname }}</h1>
    <form method="POST" action="{{ url_for('customer.edit_customer', customer_id=customer.id) }}">
    {% for key, value in customer.items() %}
        {% if key != 'id' and key != 'links' %}
            <div class="form-group">
                <label for="{{ key }}">{{ key|title }}</label>
                <input type="text" class="form-control" id="{{ key }}" name="{{ key }}" value="{{ value }}">
            </div>
        {% endif %}
    {% endfor %}
    <button type="submit" class="btn btn-primary">Update</button>
</form>
    <a href="{{ url_for('customer.delete_customer', customer_id=customer.id) }}" onclick="return confirm('Are you sure you want to delete this customer?')">Delete Customer</a>
{% endblock %}

templates/edit_rental.html
{% extends 'base.html' %}

{% block content %}
    <h1>Edit Rental</h1>
<form action="{{ url_for('rental.edit_rental', rental_id=rental.id) }}" method="post">
  {% for key, value in rental.items() %}
    {% if key != 'id' and key != 'links' and key != 'car_name' and key != 'customer_name' %}
      <div class="form-group">
        <label for="{{ key }}">{{ key|title }}</label>
        {% if key == 'status' %}
          <select class="form-control" id="{{ key }}" name="{{ key }}">
            <option value="Rented" {% if value == 'Rented' %} selected {% endif %}>Rented</option>
           <option value="Returned" {% if value == 'Returned' %} selected {% endif %}>Returned</option>
          </select>
        {% else %}
          <input type="text" class="form-control" id="{{ key }}" name="{{ key }}" value="{{ value }}">
        {% endif %}
      </div>
    {% endif %}
  {% endfor %}
  <button type="submit">Save Changes</button>
</form>
<a href="#" onclick="if (confirm('Are you sure you want to delete this Rental?')) { document.getElementById('delete-form-{{ rental.id }}').submit(); }">Delete Rental</a>
<form id="delete-form-{{ rental.id }}" action="{{ url_for('rental.delete_rental', rental_id=rental.id) }}" method="post">
{% endblock %}